version: '3'
services:
  EurekaServer:
    image: eureka-server:latest
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  ScrumMasterDashBoard:
    image: team-management:latest
    build:
      context: ./team-management
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  Spring6Test:
    image: sprint-security-management:latest
    build:
      context: ./sprint-management
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
