version: '3'
services:
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  team-management:
    image: team-management:latest
    build:
      context: ./team-management
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  sprint-management:
    image: sprint-management:latest
    build:
      context: ./sprint-management
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
