version: '3'
services:
  EurekaServer:
    image: eureka-server:latest
    build:
      context: ./EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  ScrumMasterDashBoard:
    image: scrummasterdashBoard:latest
    build:
      context: ./ScrumMasterDashBoard
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  Spring6Test:
    image: Spring6Test:latest
    build:
      context: ./Spring6Test
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
